apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ntfy
  namespace: {{ .Release.Namespace }}
  {{- if .Values.deletionProtection }}
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
  {{- end }}
  labels:
    app.kubernetes.io/name: ntfy
spec:
  storageClassName: {{ .Values.storage.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
