apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: longhorn-replica-affinity
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values: [longhorn-replica-affinity-webhook, longhorn-replica-affinity-reconciler]
  podMetricsEndpoints:
    - port: metrics
      interval: 60s
