apiVersion: v1
kind: Service
metadata:
  name: longhorn-replica-affinity-webhook
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app.kubernetes.io/name: longhorn-replica-affinity-webhook
  ports:
    - name: https
      port: 443
      targetPort: webhook
